---
name: Pull request CI workflow

on:
  pull_request:
    branches:
    - master
    - actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14'
    - run: make generate
